name: Test ftplugin
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - doc/**
      - LICENSE
      - README.md

permissions:
  contents: read

jobs:
  test-on-vim:
    name: Test on Vim ${{ matrix.vim_version }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        vim_version:
          - v9.1.0000
          - v9.2.0000
          - head
    uses: mityu/workflow-run-vim-themis/.github/workflows/run-themis.yml@v20260116
    with:
      vim_type: vim
      vim_version: ${{ matrix.vim_version }}
      os: ${{ matrix.os }}
      download: available

  test-on-neovim:
    name: Test on Neovim ${{ matrix.vim_version }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        vim_version:
          - v0.10.0
          - v0.11.0
          - v0.12.0
          - head
    uses: mityu/workflow-run-vim-themis/.github/workflows/run-themis.yml@v20260116
    with:
      vim_type: neovim
      vim_version: ${{ matrix.vim_version }}
      os: ${{ matrix.os }}
      download: available
